# Variable 'MajorVesion' was defined in the Variables tab
# Variable 'MinorVerion' was defined in the Variables tab
# Variable 'PathProjects' was defined in the Variables tab
trigger:
  branches:
    include:
    - master
resources:
  repositories:
  - repository: self
    type: git
    ref: master
jobs:
- job: Job_1
  displayName: Deploy
  pool:
    vmImage: vs2017-win2016
  steps:
  - checkout: self

  - task: NuGetCommand@2
    inputs:
      command: 'restore'
      restoreSolution: '**/*.sln'
      feedsToUse: 'select'
      vstsFeed: '09b2821a-2950-4eff-a722-dbc8adf4da55'
      noCache: true

  - task: NuGetCommand@2
    inputs:
      command: 'pack'
      packagesToPack: '**/*.csproj'
      versioningScheme: 'off'

  - task: NuGetCommand@2
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
      nuGetFeedType: 'external'
      publishFeedCredentials: 'nuget.org'