# Variable 'MajorVesion' was defined in the Variables tab
# Variable 'MinorVerion' was defined in the Variables tab
# Variable 'PathProjects' was defined in the Variables tab
trigger:
  branches:
    include:
    - master
resources:
  repositories:
  - repository: self
    type: git
    ref: master
jobs:
- job: Job_1
  displayName: Deploy
  pool:
    vmImage: vs2017-win2016
  steps:
  - checkout: self
  - task: PowerShell@2
    displayName: PowerShell Script
    inputs:
      targetType: inline
      script: "[xml] $xdoc = Get-Content \"Wiz.Multitenant.Core.nuspec\"\n$xdoc.package.metadata.version = \"1.1.$(Build.BuildNumber)\"\n$xdoc.Save(\"Wiz.Multitenant.Core.nuspec\") "

  - task: DotNetCoreCLI@2
    displayName: Restore
    inputs:
      command: 'restore'
      projects: '**/Wiz.Multitenant.Core.csproj'


  - task: DotNetCoreCLI@2
    displayName: Build
    inputs:
      command: 'build'
      projects: '**/Wiz.Multitenant.Core.csproj'
      arguments: '-c Release /p:Version=1.1.$(Build.BuildNumber).0'

  - task: DotNetCoreCLI@2
    displayName: Pack
    inputs:
      command: 'pack'
      configuration: 'Release'
      packagesToPack: '**/Wiz.Multitenant.Core.csproj'
      nobuild: true
      versioningScheme: byPrereleaseNumber 
      majorVersion: '1'
      minorVersion: '1'
      patchVersion: '$(Build.BuildNumber)' 

  - task: NuGetToolInstaller@1
    displayName: Use NuGet >= 5.x
    inputs:
      versionSpec: '>= 5.x'
      checkLatest: true

  - task: NuGetCommand@2
    displayName: NuGet pack
    inputs:
      command: push
      nuGetFeedType: external
      feedPublish: $(feed)
      externalEndpoint: $(endpoint)
      searchPatternPack: Wiz.Multitenant.Core.nuspec
      versioningScheme: byPrereleaseNumber